---
deployment:
  tasks:
    - export DEPLOYPATH=/home/medicapshosting/public_html/
    - /bin/cp -R index $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
